[project]
name = "winget-upgrade"
version = "0.1.0"
description = "Winget Upgrade"
requires-python = ">=3.14"
dependencies = [
    "pip>=25.1.1",
    "pyinstaller>=6.17.0",
    "pyqt6==6.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["winget_gui"]

[project.scripts]
winget-gui = "winget_gui.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
